apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-staging.ab1e4d0cbd41a4acca14c7fa4f60133c-1483489405.us-east-2.elb.amazonaws.com.nip.io
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-staging.svc.cluster.local
    - destination:
        host: carts-primary.sockshop-staging.svc.cluster.local
      weight: 100
